### ISSUE TITLE
 TypeError: Cannot read property 'access' of undefined

### ISSUE THREAD

**Issue by efukela** [bdistin/fs-nextra#100]
I'm getting an errors, which only happens on Centos 7 when trying to deploy one project there from my local PC (running on windows)
```TypeError: Cannot read property 'access' of undefined
    at Object.<anonymous> (/home/iskovadiana95/discord/node_modules/klasa/node_modules/fs-nextra/dist/fs.js:5:39)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/iskovadiana95/discord/node_modules/klasa/node_modules/fs-nextra/dist/index.js:6:10
)
    at Module._compile (module.js:653:30)```

**Comment by kyranet** [comment]
Do you have Node.js 10? It's required for `fs-nextra@0.4.x`

**Comment by bdistin** [comment]
I assume since there was no response that this was a version issue, and the author has fixed their problem. If that is not the case, they can return and provide more information.

**Comment by Link-lin** [comment]
I do encounter this problem when my node version is out of date. It all worked after updating the node.
